/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Disparos;
import Clases.Movimiento;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author mco_a
 */
public class Gaming extends javax.swing.JFrame {

    private Menu padre;
    private Movimiento alienNaveMovimiento;
    private ArrayList<Disparos> disparos = new ArrayList<>();

    /**
     * Creates new form Gaming
     */
    public Gaming() {
        initComponents();
        alienNaveMovimiento = new Movimiento(NaveA);
    }

    public Gaming(Menu padre) {
        initComponents();
        this.padre = padre;
    this.setFocusable(true);
    this.requestFocus(); // Añade esta línea para establecer el enfoque
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NaveA = new javax.swing.JLabel();
        NaveT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NaveA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Nave-Alienígena.png"))); // NOI18N
        jPanel1.add(NaveA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 310, 90));

        NaveT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Nave-Terrícola.png"))); // NOI18N
        jPanel1.add(NaveT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Fondo-Gaming.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (NaveT == null) {
            return; // Asegúrate de que NaveT no sea nulo
        }

        int currentX = NaveT.getX();
        int currentY = NaveT.getY();
        int newWidth = NaveT.getWidth();
        int newHeight = NaveT.getHeight();
        int step = 5; // Tamaño del paso para el movimiento

        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            disparos.add(new Disparos(NaveT.getX() + NaveT.getWidth() / 2, NaveT.getY(), 0, -10, true));
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_A && currentX - step >= 0) {
            NaveT.setBounds(currentX - step, currentY, newWidth, newHeight);
        } else if (evt.getKeyCode() == KeyEvent.VK_D && currentX + step + newWidth <= jPanel1.getWidth()) {
            NaveT.setBounds(currentX + step, currentY, newWidth, newHeight);
        }
    }//GEN-LAST:event_formKeyPressed

    public void paint(Graphics g) {
        super.paint(g);

        for (Disparos disparo : disparos) {
            disparo.run(); // Move the projectiles
            disparo.paint((java.awt.Graphics2D) g);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gaming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NaveA;
    private javax.swing.JLabel NaveT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
